# Generated by Django 5.0.7 on 2024-07-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1999-06-24'),
            preserve_default=False,
        ),
    ]
